# Generated by Django 3.2.25 on 2024-12-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20241205_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('business', 'Business'), ('rental_income', 'Rental Income'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfers')], max_length=50, null=True),
        ),
    ]
