# Generated by Django 3.2.25 on 2024-12-24 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0007_auto_20241223_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfers')], max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_category', models.CharField(choices=[('salary', 'Salary'), ('business', 'Business'), ('rental_income', 'Rental Income'), ('other', 'Other')], max_length=100, null=True)),
                ('expense_category', models.CharField(choices=[('food', 'Food'), ('social_life', 'Social Life'), ('pets', 'Pets'), ('transport', 'Transport'), ('culture', 'Culture'), ('household', 'Household'), ('apparel', 'Apparel'), ('beauty', 'Beauty'), ('health', 'Health'), ('education', 'Education'), ('gift', 'Gift')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='budget.account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='budget.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='income',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='to_account',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='to_account',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
