# Generated by Django 3.2.25 on 2024-12-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20241224_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('social_life', 'Social Life'), ('pets', 'Pets'), ('transport', 'Transport'), ('culture', 'Culture'), ('household', 'Household'), ('apparel', 'Apparel'), ('beauty', 'Beauty'), ('health', 'Health'), ('education', 'Education'), ('gift', 'Gift')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='income_category',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('business', 'Business'), ('rental_income', 'Rental Income'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
