# Generated by Django 3.2.25 on 2024-12-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20241224_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='include_account',
            field=models.BooleanField(default=True),
        ),
    ]
